### ISSUE TITLE
추가적인 기능

### ISSUE THREAD

**Issue by swjsh19** [swjsh19/Personal-Calendar-Management#3]
![image](https://github.com/swjsh19/Personal-Calendar-Management/assets/108661244/c75d384a-3cd1-438f-944d-c240b8abc2d4)
- 요일을 선택해서 해당 요일에 일정을 추가할 수 있게 만들었는데 추가적으로 어떤 기능을 더 구현할지에 대해서 코멘트 달아주세요.

**Comment by HaTToek** [comment]
저렇게 되어 있으면 이번주만 보게 되니 다른 날짜로 넘어가는 부분이 추가적으로 필요할 것 같습니다.
다른 날짜로 넘어가는게 생기면 요일을 표시해주는 부분도 추가되어야 할 것 같습니다. 그리고 추가하는 부분 ux가 매끄럽지 못한 것 같습니다.
또한 하루안에 끝내지 못하는 경우에는 2개를 등록해야하니 ux가 더 떨어지게 되는 것 같습니다.
위에 부분이 해결 되거나 또는 애자일 방법론 스프린트 읽어 보시고 같은 방법으로 하는 것도 좋다고 생각됩니다.

**Comment by dlrbxo** [comment]
해당 날짜에 못끝낸 일은 따로 우선순위로 두어 한쪽에 따로 표시해 놓는 것도 괜찮아 보여요
